### ISSUE TITLE
Strelka2 fails when running with jobs > 1

### ISSUE THREAD

**Issue by ahwanpandey** [Illumina/strelka#69]
Hello,

Strelka2 runs fine when I use "--jobs 1" but fails when jobs > 1. The command I am using is as follows. 

```
	python $STRELKA2_HOME/configureStrelkaSomaticWorkflow.py \
        --tumorBam $TUMOR_BAM \
        --normalBam $NORMAL_BAM \
        --referenceFasta $REF_FASTA \
        --runDir $OUTPUT_DIR \
        --config $EASYPIPE_HOME/WGS/Scripts/Strelka2/configureStrelkaSomaticWorkflow.py.ini \
        --region $REGION

	python $OUTPUT_DIR/runWorkflow.py \
	    --mode local \
	    --jobs $THREADS

```

Part of the output log

```
[2018-09-24T03:31:46.807837Z] [HIDDEN] [15646_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_000_1_0020] Task initiated on local node
[2018-09-24T03:31:46.810298Z] [HIDDEN] [15646_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_000_1_0002] Task initiated on local node
[2018-09-24T03:31:46.819603Z] [HIDDEN] [15646_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_000_1_0007] Task initiated on local node
[2018-09-24T03:32:16.659625Z] [HIDDEN] [15646_1] [TaskRunner:getChromDepth_removeTmpDir] [WARNING] No complete signal file found after 30 seconds, retrying after delay. Signal file path: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/005/pyflowTaskWrapper.signal.txt'
[2018-09-24T03:32:27.285814Z] [HIDDEN] [15646_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_000_1_0002] [WARNING] No complete signal file found after 30 seconds, retrying after delay. Signal file path: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/013/pyflowTaskWrapper.signal.txt'
[2018-09-24T03:32:27.943724Z] [HIDDEN] [15646_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_000_1_0020] [WARNING] No complete signal file found after 30 seconds, retrying after delay. Signal file path: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/049/pyflowTaskWrapper.signal.txt'
[2018-09-24T03:32:46.805573Z] [HIDDEN] [15646_1] [TaskRunner:getChromDepth_removeTmpDir] [WARNING] No complete signal file found after 60 seconds, retrying after delay. Signal file path: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/005/pyflowTaskWrapper.signal.txt'
[2018-09-24T03:32:51.844043Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] Failed to complete command task: 'CallGenome+callGenomeSegment_chromId_000_1_0007' launched from sub-workflow 'CallGenome', error code: 1, command: '/researchers/ahwan.pandey/Tools/omics_tools/strelka2/2.9.9/libexec/strelka2 --region 1:83083544-94952620 --ref /data/reference/indexes/human/b37/fasta/human_g1k_v37.fasta --max-indel-size 49 --min-mapping-quality 20 --somatic-snv-rate 0.0001 --shared-site-error-rate 0.0000000005 --shared-site-error-strand-bias-fraction 0.0 --somatic-indel-rate 0.000001 --shared-indel-error-factor 2.2 --tier2-min-mapping-quality 0 --strelka-snv-max-filtered-basecall-frac 0.4 --strelka-snv-max-spanning-deletion-frac 0.75 --strelka-snv-min-qss-ref 15 --strelka-indel-max-window-filtered-basecall-frac 0.3 --strelka-indel-min-qsi-ref 40 --ssnv-contam-tolerance 0.15 --indel-contam-tolerance 0.15 --somatic-snv-scoring-model-file /researchers/ahwan.pandey/Tools/omics_tools/strelka2/2.9.9/share/config/somaticSNVScoringModels.json --somatic-indel-scoring-model-file /researchers/ahwan.pandey/Tools/omics_tools/strelka2/2.9.9/share/config/somaticIndelScoringModels.json --normal-align-file /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_NormalA/Alignments/NormalA.dups_marked.sorted.recal.bam --tumor-align-file /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Alignments/TumorA.dups_marked.sorted.recal.bam --somatic-snv-file /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/genomeSegment.tmpdir/somatic.snvs.unfiltered.chromId_000_1_0007.vcf --somatic-indel-file /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/genomeSegment.tmpdir/somatic.indels.unfiltered.chromId_000_1_0007.vcf --stats-file /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/genomeSegment.tmpdir/runStats.chromId_000_1_0007.xml --strelka-skip-header --strelka-chrom-depth-file /researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/chromDepth.tsv --strelka-max-depth-factor 3.0'
[2018-09-24T03:32:51.849063Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] Error Message:
[2018-09-24T03:32:51.853169Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] Anomalous task wrapper stderr output. Wrapper signal file: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/023/pyflowTaskWrapper.signal.txt'
[2018-09-24T03:32:51.860835Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] Logging 15 line(s) of task wrapper log output below:
[2018-09-24T03:32:51.866105Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr] [2018-09-24T03:31:51.507599Z] [HIDDEN] [15646_1] [pyflowTaskWrapper:CallGenome+callGenomeSegment_chromId_000_1_0007] [wrapperSignal] wrapperStart
[2018-09-24T03:32:51.869904Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr] Traceback (most recent call last):
[2018-09-24T03:32:51.874075Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]   File "/researchers/ahwan.pandey/Tools/omics_tools/strelka2/2.9.9/lib/python/pyflow/pyflowTaskWrapper.py", line 338, in <module>
[2018-09-24T03:32:51.879199Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]     main()
[2018-09-24T03:32:51.882885Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]   File "/researchers/ahwan.pandey/Tools/omics_tools/strelka2/2.9.9/lib/python/pyflow/pyflowTaskWrapper.py", line 248, in main
[2018-09-24T03:32:51.886719Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]     params = getParams(picklefile)
[2018-09-24T03:32:51.890888Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]   File "/researchers/ahwan.pandey/Tools/omics_tools/strelka2/2.9.9/lib/python/pyflow/pyflowTaskWrapper.py", line 178, in getParams
[2018-09-24T03:32:51.894506Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]     paramhash = pickle.load(open(paramsFile))
[2018-09-24T03:32:51.898480Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]   File "/usr/lib64/python2.7/pickle.py", line 1378, in load
[2018-09-24T03:32:51.903994Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]     return Unpickler(file).load()
[2018-09-24T03:32:51.907406Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]   File "/usr/lib64/python2.7/pickle.py", line 858, in load
[2018-09-24T03:32:51.914437Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]     dispatch[key](self)
[2018-09-24T03:32:51.919755Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]   File "/usr/lib64/python2.7/pickle.py", line 880, in load_eof
[2018-09-24T03:32:51.923665Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr]     raise EOFError
[2018-09-24T03:32:51.928229Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] [CallGenome+callGenomeSegment_chromId_000_1_0007] [taskWrapper-stderr] EOFError
[2018-09-24T03:32:51.932606Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] Shutting down task submission. Waiting for remaining tasks to complete.
[2018-09-24T03:32:57.342301Z] [HIDDEN] [15646_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_000_1_0002] [WARNING] No complete signal file found after 60 seconds, retrying after delay. Signal file path: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/013/pyflowTaskWrapper.signal.txt'
[2018-09-24T03:32:58.051180Z] [HIDDEN] [15646_1] [TaskRunner:CallGenome+callGenomeSegment_chromId_000_1_0020] [WARNING] No complete signal file found after 60 seconds, retrying after delay. Signal file path: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/049/pyflowTaskWrapper.signal.txt'
[2018-09-24T03:33:04.013451Z] [HIDDEN] [15646_1] [TaskManager] [ERROR] Failed to complete sub-workflow task: 'CallGenome' launched from master workflow, failed sub-workflow classname: 'CallWorkflow'
[2018-09-24T03:33:16.845727Z] [HIDDEN] [15646_1] [TaskRunner:getChromDepth_removeTmpDir] [WARNING] No complete signal file found after 90 seconds, retrying after delay. Signal file path: '/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/005/pyflowTaskWrapper.signal.txt'


```

Please help!

Thanks.

**Comment by ctsa** [comment]
Thanks for reporting this. We haven't seen an error following this pattern before, and my best guess is this indicates some kind of odd interaction with the filesystem.

Can you provide the contents of:
 
`/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/005/pyflowTaskWrapper.signal.txt`

...and additionally list what other files are present in that directory (`/researchers/ahwan.pandey/Projects/WholeGenome/Project_DG/tests/pipeline_test_tn_paired/analysis_test/Sample_TumorA/Strelka2/intermediate/1/workspace/pyflow.data/logs/tmp/taskWrapperLogs/000/005/`) ?

**Comment by ahwanpandey** [comment]
Sorry for the delay. I have zipped the run directory on a small test file with the errors. Really looking forward to hearing back  from you!

[strelka_multi_thread_rundir.tar.gz](https://github.com/Illumina/strelka/files/2463076/strelka_multi_thread_rundir.tar.gz)


Thanks!

**Comment by ahwanpandey** [comment]
Hi @ctsa , just checking to see if you had any ideas about this issue?

Thanks!

**Comment by ctsa** [comment]
Thanks for your patience and sharing the log. I have been able to look it over for a limited time and haven't been able to pull any obvious leads from the attached logs themselves. The only thing I can suggest is from your above observation of an unpickling error -- there are some discussions of similar errors have been observed with python 2.7.5, where newer python 2.7.x versions might fix the issue. I'm a bit skeptical that this should be the cause of your observations because it would not explain why the jobs=1 case is working, but it is the only thing I can suggest at the moment -- and an unpickling error would explain an early wrapper script failure leading to the anomolous signal file message appearing in your logs.

**Comment by ctsa** [comment]
Hi @ahwanpandey , Any chance you've been able to try this with a python 2.7 version newer than 2.7.5? If it could be confirmed whether this 2.7.5 unpickle bug was involved we'd be in a better position to suggest a next step.

**Comment by ahwanpandey** [comment]
@ctsa Thanks for looking into this and sorry I haven't been prompt with my responses. I'm not sure if or when the sys admins will be able to update the python versions but I will let you know as soon as we are able to test it out!

**Comment by ahwanpandey** [comment]
Hi @ctsa.

You were right on your first guess about the issues i.e. "this indicates some kind of odd interaction with the filesystem". The server admins have applied some fixes to the filesystem and now it works perfectly fine!

Thanks for all the input and sorry for the troubles!

**Comment by ctsa** [comment]
Thanks for the update, good to hear it's working now.
